//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public override int ID { get; set; }
        public override System.Guid Key { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int GenderID { get; set; }
        public System.Guid CustomerTypeKey { get; set; }
        public override int ActivityContextID { get; set; }
        public override System.DateTime CreatedDate { get; set; }
        public override System.DateTime ModifiedDate { get; set; }
    }
}
