//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class CustomerType
    {
        public override int ID { get; set; }
        public override System.Guid Key { get; set; }
        public string Name { get; set; }
        public override System.DateTime CreatedDate { get; set; }
        public override System.DateTime ModifiedDate { get; set; }
    }
}
