--
-- CREATE LOGIN
--
-- Windows Authentication:
  -- CREATE LOGIN [Domain\FoundationUser] FROM WINDOWS WITH DEFAULT_DATABASE=[FoundationData]
  -- GO
-- SQL Server Mixed Mode:
  -- CREATE LOGIN [FoundationUser] WITH PASSWORD = 'CA9784C4-2671-41EE-A817-A1EE18373947', DEFAULT_DATABASE=[FoundationData]
  -- GO
