--
-- CREATE USER
--
-- Windows Authentication:
   -- CREATE USER [FoundationUser] FOR LOGIN [Domain\FoundationUser] WITH DEFAULT_SCHEMA=[EntityCode]
   -- GO
-- SQL Server Mixed Mode:
--   CREATE USER [FoundationUser] FOR LOGIN [FoundationUser] WITH DEFAULT_SCHEMA=[EntityCode]
--   GO
